version: '3.7'

services:
  database-service:
    image: mysql:8
    networks:
      - app-network
    ports:
      - "3306:3306"
    container_name: database-service
    environment:
      MYSQL_DATABASE: cms_db
      MYSQL_ROOT_PASSWORD: password
  backend-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: cms-ddd-architecture
    networks:
      - app-network
    container_name: backend-service
    volumes:
      - .:/app
    environment:
      NODE_ENV: development
      APP_PORT: 4000
      API_PREFIX: apis
      DATABASE_HOST: database-service
      DATABASE_PORT: 3306
      DATABASE_USER: root
      DATABASE_PASSWORD: password
      DATABASE_NAME: cms_db
      CACHE_MODE: 'memory'
    depends_on:
      - database-service
    command: pnpm --filter api-nest-app start:dev
networks:
  app-network:
    driver: bridge