export const ACCESS_SECRET = 'ACCESS_SECRET'
export const REFRESH_SECRET = 'REFRESH_SECRET'
export const QUERY_SECRET = 'QUERY_SECRET'
export const TOKEN_TYPE = 'Bearer'
export const HASH_SECRET = 'HASH_SECRET'
export const TOKEN_SECRET = 'TOKEN_SECRET'
