const JWT_SECRET = 'f8pqGisqfvm/DcwjhrG2hFESbNcJbG80NV2Zf92ZY0ZC+9dIaeKsYzqBZXwkHjLpQ2yiEOjrclBeR7NYThz/ow=='
export const ACCESS_SECRET = 'ACCESS_SECRET' + JWT_SECRET
export const REFRESH_SECRET = 'REFRESH_SECRET' + JWT_SECRET
export const QUERY_SECRET = 'QUERY_SECRET' + JWT_SECRET
export const HASH_SECRET = 'HASH_SECRET' + JWT_SECRET
export const TOKEN_TYPE = 'Bearer'
