export interface SeedToken {
  colorPrimary: string
  colorSurfaceTint: string
  colorOnPrimary: string
  colorPrimaryContainer: string
  colorOnPrimaryContainer: string
  colorSecondary: string
  colorOnSecondary: string
  colorSecondaryContainer: string
  colorOnSecondaryContainer: string
  colorTertiary: string
  colorOnTertiary: string
  colorTertiaryContainer: string
  colorOnTertiaryContainer: string
  colorError: string
  colorOnError: string
  colorErrorContainer: string
  colorOnErrorContainer: string
  colorBackground: string
  colorOnBackground: string
  colorSurface: string
  colorOnSurface: string
  colorSurfaceVariant: string
  colorOnSurfaceVariant: string
  colorOutline: string
  colorOutlineVariant: string
  colorShadow: string
  colorScrim: string
  colorInverseSurface: string
  colorInverseOnSurface: string
  colorInversePrimary: string
  colorPrimaryFixed: string
  colorOnPrimaryFixed: string
  colorPrimaryFixedDim: string
  colorOnPrimaryFixedVariant: string
  colorSecondaryFixed: string
  colorOnSecondaryFixed: string
  colorSecondaryFixedDim: string
  colorOnSecondaryFixedVariant: string
  colorTertiaryFixed: string
  colorOnTertiaryFixed: string
  colorTertiaryFixedDim: string
  colorOnTertiaryFixedVariant: string
  colorSurfaceDim: string
  colorSurfaceBright: string
  colorSurfaceContainerLowest: string
  colorSurfaceContainerLow: string
  colorSurfaceContainer: string
  colorSurfaceContainerHigh: string
  colorSurfaceContainerHighest: string
}

export const defaultSeedTokenKey = {
  colorPrimary: '#6750a4',
  colorSurfaceTint: '#6750a4',
  colorOnPrimary: '#ffffff',
  colorPrimaryContainer: '#eaddff',
  colorOnPrimaryContainer: '#21005d',
  colorSecondary: '#625b71',
  colorOnSecondary: '#ffffff',
  colorSecondaryContainer: '#e8def8',
  colorOnSecondaryContainer: '#1d192b',
  colorTertiary: '#7d5260',
  colorOnTertiary: '#ffffff',
  colorTertiaryContainer: '#ffd8e4',
  colorOnTertiaryContainer: '#410002',
  colorError: '#ba1b1b',
  colorOnError: '#ffffff',
  colorErrorContainer: '#ffdad6',
  colorOnErrorContainer: '#410e0b',
  colorBackground: '#fffbfe',
  colorOnBackground: '#1c1917',
  colorSurface: '#fffbfe',
  colorOnSurface: '#1c1917',
  colorSurfaceVariant: '#e8def8',
  colorOnSurfaceVariant: '#49454f',
  colorOutline: '#79747e',
  colorOutlineVariant: '#cccacd',
  colorShadow: 'rgba(0,0,0,0.2)',
  colorScrim: 'rgba(0,0,0,0.5)',
  colorInverseSurface: '#313033',
  colorInverseOnSurface: '#f4eff4',
  colorInversePrimary: '#d0bcff',
  colorPrimaryFixed: '#eaddff',
  colorOnPrimaryFixed: '#21005d',
  colorPrimaryFixedDim: '#e8ddff',
  colorOnPrimaryFixedVariant: '#e8ddff',
  colorSecondaryFixed: '#e8def8',
  colorOnSecondaryFixed: '#1d192b',
  colorSecondaryFixedDim: '#e8def8',
  colorOnSecondaryFixedVariant: '#e8def8',
  colorTertiaryFixed: '#ffd8e4',
  colorOnTertiaryFixed: '#410002',
  colorTertiaryFixedDim: '#ffd8e4',
  colorOnTertiaryFixedVariant: '#ffd8e4',
  colorSurfaceDim: '#e8def8',
  colorSurfaceBright: '#e8def8',
  colorSurfaceContainerLowest: '#1c1917',
  colorSurfaceContainerLow: '#1c1917',
  colorSurfaceContainer: '#1c1917',
  colorSurfaceContainerHigh: '#1c1917',
  colorSurfaceContainerHighest: '#1c1917',
} satisfies SeedToken
